import React, { useState } from 'react'
import { FiArrowLeft, FiLock, FiMail, FiX } from 'react-icons/fi'
import { apiRequest } from '../services/api'
import './AccountFlow.css'

export default function ForgotPasswordPopup({ onClose }) {
  const [step,setStep]=useState('email');const[email,setEmail]=useState('');const[otp,setOtp]=useState('');const[password,setPassword]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false)
  const proceed=async event=>{event.preventDefault();setBusy(true);setMessage('');try{if(step==='email'){await apiRequest('/api/auth/forgot/start',{method:'POST',body:{email}});setStep('otp');setMessage('A verification code was sent to your email')}else if(step==='otp'){await apiRequest('/api/auth/forgot/verify',{method:'POST',body:{email,otp}});setStep('reset')}else{await apiRequest('/api/auth/forgot/reset',{method:'POST',body:{email,otp,newPassword:password}});setMessage('Password updated successfully');window.setTimeout(()=>onClose?.(),1000)}}catch(reason){setMessage(reason.message||'Unable to continue')}finally{setBusy(false)}}
  return <div className="tara-auth-overlay"><div className="tara-auth-card"><button className="tara-auth-close" onClick={onClose}><FiX/></button><span className="tara-auth-kicker">Account recovery</span><h2>{step==='email'?'Reset your password':step==='otp'?'Enter verification code':'Choose a new password'}</h2><p>{step==='email'?'We will send a secure code to your registered email.':step==='otp'?`Enter the 6 digit code sent to ${email}.`:'Use at least 6 characters for your new password.'}</p><form onSubmit={proceed}>{step==='email'&&<label><span>Email address</span><div><FiMail/><input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></div></label>}{step==='otp'&&<label><span>Verification code</span><div><input className="tara-auth-otp" value={otp} onChange={event=>setOtp(event.target.value.replace(/\D/g,'').slice(0,6))}/></div></label>}{step==='reset'&&<label><span>New password</span><div><FiLock/><input type="password" value={password} onChange={event=>setPassword(event.target.value)}/></div></label>}{message&&<div className="tara-auth-message">{message}</div>}<button className="tara-auth-submit" disabled={busy}>{busy?'Please wait':step==='email'?'Send code':step==='otp'?'Verify code':'Update password'}</button>{step!=='email'&&<button type="button" className="tara-auth-back" onClick={()=>setStep(step==='reset'?'otp':'email')}><FiArrowLeft/>Back</button>}</form></div></div>
}
