import React, { useEffect, useState } from 'react'
import { FiGift, FiHelpCircle, FiLogOut, FiPackage, FiRefreshCw, FiUser } from 'react-icons/fi'
import { useLocation, useNavigate } from 'react-router-dom'
import { clearUser, fetchUser, fetchWallet, sessionUser, updateMobile } from '../services/accountApi'
import LoginPopup from './LoginPopup'
import Orders from './Orders'
import ReturnsPage from './ReturnsPage'
import Contactus from './Contactus'
import './AccountPages.css'

export default function Profile() {
  const location=useLocation();const navigate=useNavigate();const[section,setSection]=useState(location.state?.openSection||'Profile');const[user,setUser]=useState(sessionUser());const[profile,setProfile]=useState(null);const[coins,setCoins]=useState(0);const[mobile,setMobile]=useState(user.mobile||'');const[message,setMessage]=useState('');const[showLogin,setShowLogin]=useState(false)
  const userEmail=user.email||''
  useEffect(()=>{if(!userEmail)return;fetchUser(userEmail).then(data=>{setProfile(data);setMobile(data.mobile||'')}).catch(()=>setProfile(current=>current||sessionUser()));fetchWallet(userEmail).then(data=>setCoins(Number(data.balance||0))).catch(()=>{})},[userEmail])
  const loggedIn=Boolean(user.id||user.email)
  const saveMobile=async()=>{if(!/^[6-9]\d{9}$/.test(mobile))return setMessage('Enter a valid 10 digit mobile number');try{await updateMobile({email:user.email,mobile});sessionStorage.setItem('userMobile',mobile);localStorage.setItem('userMobile',mobile);setMessage('Mobile number saved')}catch(reason){setMessage(reason.message||'Unable to save mobile number')}}
  const logout=()=>{clearUser();navigate('/');window.location.reload()}
  if(!loggedIn)return <main className="tara-account-page"><div className="tara-account-login"><FiUser/><span>Your Tara account</span><h1>Sign in to manage everything</h1><p>View orders, track deliveries, request returns and use Tara Coins.</p><button onClick={()=>setShowLogin(true)}>Sign in</button>{showLogin&&<LoginPopup onClose={()=>setShowLogin(false)} onSuccess={data=>{setUser(sessionUser());setProfile(data)}}/>}</div></main>
  const name=profile?.name||user.name||user.email?.split('@')[0]||'Customer'
  return <main className="tara-account-page">{message&&<div className="tara-account-toast">{message}</div>}<header className="tara-account-hero"><span>My account</span><h1>Hello, {name}</h1><p>{user.email}</p></header><div className="tara-account-layout"><aside className="tara-account-nav"><div className="tara-account-avatar">{name.slice(0,1).toUpperCase()}</div><strong>{name}</strong><small>{String(user.type||'B2C').toUpperCase()} account</small><nav><Nav icon={<FiUser/>} label="Profile" active={section==='Profile'} onClick={()=>setSection('Profile')}/><Nav icon={<FiPackage/>} label="Orders" active={section==='Orders'} onClick={()=>setSection('Orders')}/><Nav icon={<FiRefreshCw/>} label="Returns" active={section==='Returns'} onClick={()=>setSection('Returns')}/><Nav icon={<FiGift/>} label="Coin wallet" active={section==='Coins'} onClick={()=>setSection('Coins')}/><Nav icon={<FiHelpCircle/>} label="Customer care" active={section==='Support'} onClick={()=>setSection('Support')}/></nav><button className="tara-account-logout" onClick={logout}><FiLogOut/>Sign out</button></aside><section className="tara-account-content">{section==='Profile'&&<div className="tara-profile-panel"><span>Personal details</span><h2>Your profile</h2><div className="tara-profile-fields"><label><span>Name</span><input value={name} disabled/></label><label><span>Email</span><input value={user.email||''} disabled/></label><label><span>Mobile number</span><input value={mobile} onChange={event=>setMobile(event.target.value.replace(/\D/g,'').slice(0,10))}/></label></div><button onClick={saveMobile}>Save changes</button></div>}{section==='Orders'&&<Orders user={{...user,...profile}}/>}{section==='Returns'&&<ReturnsPage embedded/>}{section==='Coins'&&<div className="tara-coins-panel"><FiGift/><span>Tara Coin wallet</span><h2>{coins.toLocaleString('en-IN')} coins</h2><p>Use eligible coins during checkout to reduce your payable amount.</p><button onClick={()=>navigate('/')}>Start shopping</button></div>}{section==='Support'&&<Contactus embedded/>}</section></div></main>
}
function Nav({icon,label,active,onClick}){return <button className={active?'is-active':''} onClick={onClick}>{icon}{label}</button>}
