import React,{useEffect,useState} from 'react'
import {Heart,Menu,Search,ShoppingBag,UserRound,X,ArrowRight} from 'lucide-react'
import {Link,useNavigate} from 'react-router-dom'
import {api} from './api'
import {useStore} from './store'
import {money,priceFor} from './products'

export function Header(){const {user,cartCount,isB2B}=useStore();const [open,setOpen]=useState(false);const [q,setQ]=useState('');const nav=useNavigate();const submit=e=>{e.preventDefault();if(q.trim())nav(`/search?q=${encodeURIComponent(q.trim())}`)};return <><div className="announcement">Free delivery above ₹1,000 <span/> Secure payments <span/> Easy support</div><header className="header"><Link className="logo" to={isB2B?'/b2b-dashboard':'/'}><strong>Attach</strong><small>SHOPPING MALL</small></Link><nav className={open?'nav open':'nav'}>{!isB2B&&<><Link to="/women">Women</Link><Link to="/men">Men</Link><Link to="/kids">Kids</Link><Link to="/collection">Collections</Link></>} {isB2B&&<Link to="/b2b-dashboard">Wholesale</Link>}<Link to="/contact">Stores & Support</Link></nav><form className="search" onSubmit={submit}><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, brands and categories"/></form><div className="head-actions"><Link to="/wishlist" aria-label="Wishlist"><Heart/></Link><Link to="/cart" className="bag" aria-label="Cart"><ShoppingBag/>{cartCount>0&&<b>{cartCount}</b>}</Link><Link to={user?'/profile':'/auth'} aria-label="Account"><UserRound/></Link><button onClick={()=>setOpen(!open)} className="menu">{open?<X/>:<Menu/>}</button></div></header></>}

export function Footer(){return <footer><div><div className="logo light"><strong>TARA’S</strong><small>SHOPPING MALL</small></div><p>Fashion, comfort and trusted shopping for retail and wholesale customers.</p></div><div><h4>Shop</h4><Link to="/women">Women</Link><Link to="/men">Men</Link><Link to="/kids">Kids</Link><Link to="/b2b-dashboard">Wholesale</Link></div><div><h4>Help</h4><Link to="/track-order">Track order</Link><Link to="/contact">Contact</Link><Link to="/terms">Policies</Link><Link to="/privacy-policy">Privacy</Link></div><div><h4>Visit us</h4><p>Five branches across Andhra Pradesh</p><Link to="/contact">Find a store <ArrowRight size={15}/></Link></div></footer>}

export function ProductCard({product}){const {isB2B,user,wishlistIds,refresh}=useStore();const p=priceFor(product,isB2B);const off=p.original>p.final?Math.round((p.original-p.final)*100/p.original):0;const liked=wishlistIds.has(String(product.variantId));const toggle=async e=>{e.preventDefault();if(!user){location.href='/auth';return}const body={user_id:user.id,product_id:product.variantId||product.productId,variant_id:product.variantId,actual_product_id:product.productId};liked?await api.removeWishlist(body):await api.addWishlist(body);refresh()};return <Link className="product-card" to={`/product/${encodeURIComponent(product.design)}`} state={{product}}><div className="product-media">{off>0&&<span className="sale">{off}% OFF</span>}<button className={liked?'heart liked':'heart'} onClick={toggle}><Heart size={18}/></button><img src={product.images[0]} alt={product.name} onError={e=>{e.currentTarget.src='/images/women/women20.jpeg'}}/>{product.images[1]&&<img className="hover-img" src={product.images[1]} alt=""/>}</div><div className="product-copy"><small>{product.brand}</small><h3>{product.name}</h3><div><strong>{money(p.final)}</strong>{p.original>p.final&&<del>{money(p.original)}</del>}</div><p>{isB2B?'Wholesale price':'Inclusive of taxes'}</p></div></Link>}

export function SkeletonGrid(){return <div className="product-grid">{Array.from({length:8},(_,i)=><div className="skeleton" key={i}/>)}</div>}

export function Empty({title='Nothing here yet',text='Try another category or clear your filters.'}){return <div className="empty"><div>✦</div><h2>{title}</h2><p>{text}</p><Link className="btn" to="/collection">Explore products</Link></div>}
